background_b: 255
background_g: 86
background_r: 150
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_jyrig_asus__50953: 'http://JYRIG-ASUS:50953/'}
rosversion: '1.12.14

  '
run_id: 977573d2-3b3b-11e9-a67b-00ffe3dc9778
