<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="five_wheeler">
  
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0" />
    </inertial>
  </xacro:macro>
    
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  
  <xacro:property name="body_w" value="0.5" />
  <xacro:property name="body_l" value="0.8" />
  <xacro:property name="body_h" value="0.2" />
  <xacro:property name="wheel_r" value="0.2" />
  <xacro:property name="wheel_h" value="0.05" />
  <xacro:property name="wheel_offset" value="0.1" />
  <xacro:property name="body_height" value="0.2" />
  <xacro:property name="extension_l" value="0.2" />
  
  <link name="base_link" > 
    <visual>
      <geometry>
        <box size="${body_l} ${body_w}  ${body_h}" />
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${wheel_r}"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_l} ${body_h}  ${body_w}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${wheel_r}"/>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>
  
  
  <link name="left_front_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${wheel_h/2} 0 0"/>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${wheel_h/2} 0 0"/>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>
  <joint name="base_to_left_front_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin rpy= "0 0 ${pi/2}" xyz="${body_l/2 - wheel_offset} ${body_w/2} ${wheel_r}"/>
  </joint>
  
  <link name="left_back_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${wheel_h/2} 0 0"/>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${wheel_h/2} 0 0"/>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>
  <joint name="base_to_right_front_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="left_back_wheel"/>
    <origin rpy= "0 0 ${pi/2}" xyz="${-body_l/2 + wheel_offset} ${body_w/2} ${wheel_r}"/>
  </joint>
  
  <link name="right_front_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${-wheel_h/2} 0 0"/>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${-wheel_h/2} 0 0"/>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>
  <joint name="base_to_left_back_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin rpy= "0 0 ${pi/2}" xyz="${body_l/2 - wheel_offset} ${-body_w/2} ${wheel_r}"/>
  </joint>
  
  <link name="right_back_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${-wheel_h/2} 0 0"/>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${-wheel_h/2} 0 0"/>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>
  <joint name="base_to_right_back_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="right_back_wheel"/>
    <origin rpy= "0 0 ${pi/2}" xyz="${-body_l/2 + wheel_offset} ${-body_w/2} ${wheel_r}"/>
  </joint>
  
  <link name="front_extension" > 
    <visual>
      <geometry>
        <box size="${wheel_r+wheel_offset} ${body_w/2 - wheel_h/2}  ${body_h}" />
      </geometry>
      <origin rpy="0 0 0" xyz="${(wheel_r+wheel_offset)/2} ${(body_w/2 - wheel_h/2)/2} 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${wheel_r+wheel_offset} ${body_w/2 - wheel_h/2}  ${body_h}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${(wheel_r+wheel_offset)/2} ${(body_w/2 - wheel_h/2)/2} 0"/>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>
    <joint name="base_to_front extension" type="fixed">
    <parent link="base_link"/>
    <child link="front_extension"/>
    <origin xyz="${body_l/2} ${-body_w/2} ${wheel_r}"/>
  </joint>
  
  <link name="front_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${wheel_h/2} 0 0"/>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_r}" length="${wheel_h}"/>
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${wheel_h/2} 0 0"/>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>
  <joint name="extension_to_front_wheel" type="continuous">
    <parent link="front_extension"/>
    <child link="front_wheel"/>
    <origin rpy= "0 0 ${pi/2}" xyz="${wheel_r+wheel_offset/2} ${body_w/2 - wheel_h/2} 0"/>
  </joint>
  
  <link name="base_footprint" > 
  </link>
  <joint name="base_footprint_to_base" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  
</robot>
